# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: For Hi's Blog
email: your-email@domain.com
description:  Too young too simple.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rd171.github.io" # the base hostname & protocol for your site
safe: false
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

# counter
baidu-analysis： xxxxxxxxxxxxxxxxxxxxxxxxxxx
